// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: shoal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query: "announce"
// Task → Sidecar. Task-initiated registration.
// Node identity is available via q.SourceNode() — not included here.
//
// Query: "solicit"
// Sidecar → Tasks. Sidecar requests all tasks re-announce themselves.
// Tasks respond with AnnounceRequest (same payload, no separate message needed).
type AnnounceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`       // private IP the task is bound on
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`      // ephemeral port from getsockname()
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"` // "webservers" — the backend in haproxy
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`     // "ready" — sidecar ignores non-ready announces
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	mi := &file_shoal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_shoal_proto_rawDescGZIP(), []int{0}
}

func (x *AnnounceRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *AnnounceRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AnnounceRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *AnnounceRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Response to "announce" only. "solicit" responses are AnnounceRequest.
type AnnounceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	BackendKey    string                 `protobuf:"bytes,2,opt,name=backend_key,json=backendKey,proto3" json:"backend_key,omitempty"` // HAProxy server name assigned, e.g. "pool/task-abc123"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                           // populated when accepted=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceResponse) Reset() {
	*x = AnnounceResponse{}
	mi := &file_shoal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceResponse) ProtoMessage() {}

func (x *AnnounceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceResponse.ProtoReflect.Descriptor instead.
func (*AnnounceResponse) Descriptor() ([]byte, []int) {
	return file_shoal_proto_rawDescGZIP(), []int{1}
}

func (x *AnnounceResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AnnounceResponse) GetBackendKey() string {
	if x != nil {
		return x.BackendKey
	}
	return ""
}

func (x *AnnounceResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Query: "depart"
// Task → Sidecar. Signals graceful shutdown — sidecar removes backend before task exits.
type DepartRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Addr           string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port           uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // how long the task will drain; 0 = immediate
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepartRequest) Reset() {
	*x = DepartRequest{}
	mi := &file_shoal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartRequest) ProtoMessage() {}

func (x *DepartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartRequest.ProtoReflect.Descriptor instead.
func (*DepartRequest) Descriptor() ([]byte, []int) {
	return file_shoal_proto_rawDescGZIP(), []int{2}
}

func (x *DepartRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DepartRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DepartRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type DepartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartResponse) Reset() {
	*x = DepartResponse{}
	mi := &file_shoal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartResponse) ProtoMessage() {}

func (x *DepartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartResponse.ProtoReflect.Descriptor instead.
func (*DepartResponse) Descriptor() ([]byte, []int) {
	return file_shoal_proto_rawDescGZIP(), []int{3}
}

func (x *DepartResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DepartResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_shoal_proto protoreflect.FileDescriptor

const file_shoal_proto_rawDesc = "" +
	"\n" +
	"\vshoal.proto\x12\bshoal.v1\"i\n" +
	"\x0fAnnounceRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"g\n" +
	"\x10AnnounceResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vbackend_key\x18\x02 \x01(\tR\n" +
	"backendKey\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"`\n" +
	"\rDepartRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\"D\n" +
	"\x0eDepartResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB*Z(github.com/davidbirdsong/shoal/pkg/protob\x06proto3"

var (
	file_shoal_proto_rawDescOnce sync.Once
	file_shoal_proto_rawDescData []byte
)

func file_shoal_proto_rawDescGZIP() []byte {
	file_shoal_proto_rawDescOnce.Do(func() {
		file_shoal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoal_proto_rawDesc), len(file_shoal_proto_rawDesc)))
	})
	return file_shoal_proto_rawDescData
}

var file_shoal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shoal_proto_goTypes = []any{
	(*AnnounceRequest)(nil),  // 0: shoal.v1.AnnounceRequest
	(*AnnounceResponse)(nil), // 1: shoal.v1.AnnounceResponse
	(*DepartRequest)(nil),    // 2: shoal.v1.DepartRequest
	(*DepartResponse)(nil),   // 3: shoal.v1.DepartResponse
}
var file_shoal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shoal_proto_init() }
func file_shoal_proto_init() {
	if File_shoal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoal_proto_rawDesc), len(file_shoal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shoal_proto_goTypes,
		DependencyIndexes: file_shoal_proto_depIdxs,
		MessageInfos:      file_shoal_proto_msgTypes,
	}.Build()
	File_shoal_proto = out.File
	file_shoal_proto_goTypes = nil
	file_shoal_proto_depIdxs = nil
}
